-- =========================================================================
-- SUPABASE POSTGRES MIGRATION: TRIAL BOOKING SYSTEM
-- =========================================================================

-- -------------------------------------------------------------------------
-- 1. TABLE: parents
-- -------------------------------------------------------------------------
-- -------------------------------------------------------------------------
-- 1. TABLE: parents
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS parents (
    parents_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parents_uuid varchar(36) DEFAULT gen_random_uuid()::text UNIQUE NOT NULL,
    parents_user_uuid varchar(36),
    parents_name varchar,
    parents_email varchar,
    parents_phone varchar,
    parents_create_date timestamptz DEFAULT now(),
    parents_create_by varchar,
    parents_status smallint DEFAULT 1
);


-- -------------------------------------------------------------------------
-- 2. TABLE: students
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS students (
    students_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    students_uuid varchar(36) DEFAULT gen_random_uuid()::text UNIQUE NOT NULL,

    -- Hanya menyimpan UUID parent, TANPA foreign key
    students_parents_uuid varchar(36),

    students_name varchar,
    students_age int,
    students_create_date timestamptz DEFAULT now(),
    students_create_by varchar,
    students_status smallint DEFAULT 1
);


-- -------------------------------------------------------------------------
-- 3. TABLE: trial_classes
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS trial_classes (
    trial_classes_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trial_classes_uuid varchar(36) DEFAULT gen_random_uuid()::text UNIQUE NOT NULL,

    trial_classes_subject varchar,
    trial_classes_start_time timestamptz,
    trial_classes_capacity int DEFAULT 4,
    trial_classes_confirmed_count int DEFAULT 0,

    trial_classes_create_date timestamptz DEFAULT now(),
    trial_classes_create_by varchar,
    trial_classes_status smallint DEFAULT 1
);


-- -------------------------------------------------------------------------
-- 4. TABLE: bookings
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS bookings (
    bookings_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bookings_uuid varchar(36) DEFAULT gen_random_uuid()::text UNIQUE NOT NULL,

    -- Hanya menyimpan UUID student, TANPA foreign key
    bookings_students_uuid varchar(36),

    -- Hanya menyimpan UUID trial class, TANPA foreign key
    bookings_trial_classes_uuid varchar(36),

    bookings_state varchar DEFAULT 'pending_payment',
    bookings_create_date timestamptz DEFAULT now(),
    bookings_create_by varchar,
    bookings_status smallint DEFAULT 1,

    CONSTRAINT check_bookings_state
        CHECK (
            bookings_state IN (
                'pending_payment',
                'confirmed',
                'payment_failed',
                'cancelled'
            )
        )
);


-- Anti duplicate confirmed booking
CREATE UNIQUE INDEX IF NOT EXISTS bookings_students_trial_classes_confirmed_idx
ON bookings (
    bookings_students_uuid,
    bookings_trial_classes_uuid
)
WHERE bookings_state = 'confirmed';


-- -------------------------------------------------------------------------
-- 5. TABLE: payment_attempts
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS payment_attempts (
    payment_attempts_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_attempts_uuid varchar(36) DEFAULT gen_random_uuid()::text UNIQUE NOT NULL,

    -- Hanya menyimpan UUID booking, TANPA foreign key
    payment_attempts_bookings_uuid varchar(36),

    payment_attempts_result varchar,
    payment_attempts_amount numeric(10,2),
    payment_attempts_create_date timestamptz DEFAULT now(),
    payment_attempts_create_by varchar,
    payment_attempts_status smallint DEFAULT 1
);

-- -------------------------------------------------------------------------
-- 6. POSTGRES RPC FUNCTION: book_trial_class
-- -------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION book_trial_class(
    p_student_uuid varchar(36),
    p_class_uuid varchar(36),
    p_payment_success boolean
) 
RETURNS TABLE (
    r_bookings_state varchar,
    r_bookings_uuid varchar(36)
) 
LANGUAGE plpgsql
AS $$
DECLARE
    v_class_capacity int;
    v_class_confirmed int;
    v_booking_uuid varchar(36);
    v_booking_state varchar;
    v_payment_result varchar;
    v_duplicate_exists boolean;
BEGIN
    -- 1. Cek apakah sudah ada bookings_state='confirmed' untuk student+class yang sama
    SELECT EXISTS (
        SELECT 1 
        FROM bookings b
        WHERE b.bookings_students_uuid = p_student_uuid 
          AND b.bookings_trial_classes_uuid = p_class_uuid 
          AND b.bookings_state = 'confirmed'
    ) INTO v_duplicate_exists;

    IF v_duplicate_exists THEN
        RAISE EXCEPTION 'DUPLICATE_BOOKING: Student already has a confirmed booking for this class';
    END IF;

    -- 2. Lock row trial_classes terkait menggunakan SELECT ... FOR UPDATE untuk menghindari race conditions
    SELECT trial_classes_capacity, trial_classes_confirmed_count
    INTO v_class_capacity, v_class_confirmed
    FROM trial_classes
    WHERE trial_classes_uuid = p_class_uuid
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'CLASS_NOT_FOUND: Trial class does not exist';
    END IF;

    -- 3. Cek kapasitas apakah masih mencukupi
    IF v_class_confirmed >= v_class_capacity THEN
        RAISE EXCEPTION 'CLASS_FULL: The trial class capacity has been reached';
    END IF;

    -- Generate UUID baru untuk booking agar bisa direferensikan oleh payment attempt
    v_booking_uuid := gen_random_uuid()::text;

    -- 4. Insert row bookings dengan status awal 'pending_payment'
    INSERT INTO bookings (
        bookings_uuid,
        bookings_students_uuid,
        bookings_trial_classes_uuid,
        bookings_state,
        bookings_create_by
    ) VALUES (
        v_booking_uuid,
        p_student_uuid,
        p_class_uuid,
        'pending_payment',
        'system_rpc'
    );

    -- Tentukan result payment
    IF p_payment_success THEN
        v_payment_result := 'success';
        v_booking_state := 'confirmed';
    ELSE
        v_payment_result := 'failed';
        v_booking_state := 'payment_failed';
    END IF;

    -- 5. Insert row payment_attempts sesuai hasil pembayaran
    INSERT INTO payment_attempts (
        payment_attempts_bookings_uuid,
        payment_attempts_result,
        payment_attempts_amount,
        payment_attempts_create_by
    ) VALUES (
        v_booking_uuid,
        v_payment_result,
        150000.00, -- Dummy atau nominal standard
        'system_rpc'
    );

    -- 6. Update bookings_state berdasarkan status pembayaran
    UPDATE bookings b
    SET bookings_state = v_booking_state
    WHERE b.bookings_uuid = v_booking_uuid;

    -- 7. Jika payment sukses (confirmed), increment trial_classes_confirmed_count +1
    IF p_payment_success THEN
        UPDATE trial_classes
        SET trial_classes_confirmed_count = trial_classes_confirmed_count + 1
        WHERE trial_classes_uuid = p_class_uuid;
    END IF;

    -- 8. Kembalikan state akhir dan uuid booking
    RETURN QUERY SELECT v_booking_state::varchar, v_booking_uuid::varchar(36);
END;
$$;

-- -------------------------------------------------------------------------
-- 7. SEED DATA
-- -------------------------------------------------------------------------

-- Parents
INSERT INTO parents (
    parents_uuid,
    parents_name,
    parents_email,
    parents_phone,
    parents_create_by
) VALUES
('550e8400-e29b-41d4-a716-446655440001', 'Budi Santoso', 'budi@example.com', '08123456789', 'seed'),
('550e8400-e29b-41d4-a716-446655440002', 'Siti Rahma', 'siti@example.com', '08129876543', 'seed'),
('550e8400-e29b-41d4-a716-446655440003', 'Muhammad Wildan', 'joko@example.com', '08131122334', 'seed'),
('550e8400-e29b-41d4-a716-446655440004', 'Nunu Marfuah', 'ani@example.com', '08145566778', 'seed');


-- Students
INSERT INTO students (
    students_uuid,
    students_parents_uuid,
    students_name,
    students_age,
    students_create_by
) VALUES
('660e8400-e29b-41d4-a716-446655440001', '550e8400-e29b-41d4-a716-446655440001', 'Andi Santoso', 8, 'seed'),
('660e8400-e29b-41d4-a716-446655440002', '550e8400-e29b-41d4-a716-446655440002', 'Roni Rahma', 9, 'seed'),
('660e8400-e29b-41d4-a716-446655440003', '550e8400-e29b-41d4-a716-446655440003', 'Rizky Ibrahim', 10, 'seed'),
('660e8400-e29b-41d4-a716-446655440004', '550e8400-e29b-41d4-a716-446655440003', 'Maqil Ibrahim', 7, 'seed'),
('660e8400-e29b-41d4-a716-446655440005', '550e8400-e29b-41d4-a716-446655440004', 'Citra Lestari', 8, 'seed');


-- Trial Classes
INSERT INTO trial_classes (
    trial_classes_uuid,
    trial_classes_subject,
    trial_classes_start_time,
    trial_classes_capacity,
    trial_classes_confirmed_count,
    trial_classes_create_by
) VALUES
-- Class kosong (0/4)
('770e8400-e29b-41d4-a716-446655440001',
 'Coding Scratch Basic',
 now() + interval '1 day',
 4,
 0,
 'seed'),

-- Class hampir penuh (3/4)
('770e8400-e29b-41d4-a716-446655440002',
 'Python Junior Developer',
 now() + interval '2 days',
 4,
 3,
 'seed');


-- Seed 3 confirmed bookings untuk class Python Junior Developer
INSERT INTO bookings (
    bookings_uuid,
    bookings_students_uuid,
    bookings_trial_classes_uuid,
    bookings_state,
    bookings_create_by
) VALUES
(
    '880e8400-e29b-41d4-a716-446655440001',
    '660e8400-e29b-41d4-a716-446655440001',
    '770e8400-e29b-41d4-a716-446655440002',
    'confirmed',
    'seed'
),
(
    '880e8400-e29b-41d4-a716-446655440002',
    '660e8400-e29b-41d4-a716-446655440002',
    '770e8400-e29b-41d4-a716-446655440002',
    'confirmed',
    'seed'
),
(
    '880e8400-e29b-41d4-a716-446655440003',
    '660e8400-e29b-41d4-a716-446655440003',
    '770e8400-e29b-41d4-a716-446655440002',
    'confirmed',
    'seed'
);


-- Payment attempts untuk confirmed bookings
INSERT INTO payment_attempts (
    payment_attempts_bookings_uuid,
    payment_attempts_result,
    payment_attempts_amount,
    payment_attempts_create_by
) VALUES
(
    '880e8400-e29b-41d4-a716-446655440001',
    'success',
    150000.00,
    'seed'
),
(
    '880e8400-e29b-41d4-a716-446655440002',
    'success',
    150000.00,
    'seed'
),
(
    '880e8400-e29b-41d4-a716-446655440003',
    'success',
    150000.00,
    'seed'
);